name: Build FNaF World C Edition

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-raylib

      - name: Build using GCC
        shell: msys2 {0}
        run: |
          gcc -o FNAFWorld.exe src/*.c -lraylib -lwinmm -lgdi32

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fnafworld-windows
          path: FNAFWorld.exe
